language: java
jdk:
- oraclejdk7
sudo: required

install: 
  - travis_retry pip install --upgrade pip
  - export PATH=$PATH:$HOME/.local/bin
  - python --version
  - travis_retry pip install ecs-deploy
  - travis_retry pip install --user awscli

services:
 - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
 - mvn clean install
 - mvn checkstyle:check

after_success:
 - docker --version
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
 - mv app/target/itemviewerservice.war docker/
 - cd $TRAVIS_BUILD_DIR
 - chmod ugo+x DeployScripts/code_deploy.sh
 - chmod ugo+x DeployScripts/deploy.sh

deploy:
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/code_deploy.sh
    on:
      all_branches: true
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/deploy.sh ItemViewerService-prod ItemViewerService-prod
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ./DeployScripts/deploy.sh ItemViewerService-dev ItemViewerService-prod
    on:
      branch: dev

