language: java
jdk:
- oraclejdk7
sudo: required

install: 
  - export PATH=$PATH:$HOME/.local/bin
  - python --version
  - pip install ecs-deploy
  - echo $?
  - pip install --user awscli
  - echo $?

services:
 - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
 - mvn clean install
 - mvn checkstyle:check

after_success:
 - docker --version
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
 - mv app/target/itemviewerservice.war docker/
 - cd docker
 - docker build -f Dockerfile.code -t itemviewerservice .
 - docker tag itemviewerservice:latest osucass/itemviewerservicecode:$BRANCH
 - docker push osucass/itemviewerservicecode:$BRANCH
 - cd ..
 - chmod ugo+x DeployScripts/runEcsBuild.sh
 - ./DeployScripts/runEcsBuild.sh
