language: java
jdk:
- oraclejdk7
sudo: required

services:
 - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
- mvn checkstyle:check
- mvn clean install

after_success:
 - docker --version
 - pip install --user awscli
 - export PATH=$PATH:$HOME/.local/bin
 - eval $(aws ecr get-login --region us-west-2)
 - mv app/target/itemviewerservice.war docker/
 - cd docker
 - docker build -t itemviewerservice .
 - docker tag itemviewerservice:latest 047189625337.dkr.ecr.us-west-2.amazonaws.com/itemviewerservicecode:$BRANCH
 - docker push 047189625337.dkr.ecr.us-west-2.amazonaws.com/itemviewerservicecode:$BRANCH
 - chmod ugo+x DeployScripts/runEcsBuild.sh
 - ./DeployScripts/runEcsBuild.sh
