language: java
jdk:
- oraclejdk7
sudo: required

services:
 - docker

before_script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

script:
- mvn checkstyle:check
- mvn clean install

after_success:
 - docker --version
 - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
 - pip install --user awscli
 - export PATH=$PATH:$HOME/.local/bin
 - mv app/target/itemviewerservice.war docker/
 - cd docker
 - docker build -f Dockerfile.code -t itemviewerservice .
 - docker tag itemviewerservice:latest osucass/itemviewerservicecode:$BRANCH
 - docker push osucass/itemviewerservicecode:$BRANCH
 - cd ..
 - chmod ugo+x DeployScripts/runEcsBuild.sh
 - ./DeployScripts/runEcsBuild.sh
