FROM tomcat:7-jre7

WORKDIR /usr/local/tomcat/
ARG contextName=ROOT

COPY context.xml ./conf
RUN  rm -rf webapps/*

COPY itemviewerservice.war ./webapps
RUN mv ./webapps/itemviewerservice.war ./webapps/$contextName.war

ENTRYPOINT ["catalina.sh", "run"]